stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载阿里巴巴 JDK 17
    - wget https://github.com/alibaba/dragonwell17/releases/download/dragonwell-17.0.1.0.1%2B12_jdk-17.0.1-ga/Alibaba_Dragonwell_17.0.1.0.1+12_x64_linux.tar.gz
    - docker build -t dragonwell17:17.0.1.0.1-12 .
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag dragonwell17:17.0.1.0.1-12 $DOCKER_USERNAME/dragonwell17:17.0.1.0.1-12
    - docker images
    - docker push $DOCKER_USERNAME/dragonwell17:17.0.1.0.1-12
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
