stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    # 下载阿里巴巴 JDK 17
    - wget https://github.com/alibaba/dragonwell17/releases/download/dragonwell-17.0.2.0.2%2B8_jdk-17.0.2-ga/Alibaba_Dragonwell_17.0.2.0.2+8_x64_linux.tar.gz
    - docker build -t dragonwell17:17.0.2.0.2-8 .
  after_script:
    - docker images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker tag dragonwell17:17.0.2.0.2-8 $DOCKER_USERNAME/dragonwell17:17.0.2.0.2-8
    - docker images
    - docker push $DOCKER_USERNAME/dragonwell17:17.0.2.0.2-8
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  rules:
    - if: $CI_COMMIT_TAG
